### ISSUE TITLE
Commit messages before 23/03/2022 should be edited

### ISSUE THREAD

**Issue by Ndpnt** [OpenTermsArchive/france-versions#1]
There is 3 weeks worth of history in Mongo for France. The commit messages reference commit hashes but these IDs are Mongo IDs, not commit hashes, until 24th of March 2022 and commit sha c067713.

**Comment by MattiSG** [comment]
I see in 6f999c1ed4d016ed5ff64c9f7c9566c2bb0c5e64 that the identifier length went down to 7 characters, leading me to suspect an actual commit hash, but that the text still refers to a Mongo ID. Is this normal? 🙂

**Comment by Ndpnt** [comment]
> I see in [6f999c1](https://github.com/OpenTermsArchive/versions-france/commit/6f999c1ed4d016ed5ff64c9f7c9566c2bb0c5e64) that the identifier length went down to 7 characters, leading me to suspect an actual commit hash, but that the text still refers to a Mongo ID. Is this normal? 🙂

No it was an error, I fixed it.

**Comment by Ndpnt** [comment]
Fixed by integration Mongo history and changing references.

**Comment by MattiSG** [comment]
Thank you! This morning we had a use case where accessing the snapshot directly through the comment was really super useful (a PDF file that is not readable, cf. https://github.com/OpenTermsArchive/france-versions/commit/d4a1f3bea9300e73f7d1c0a9acc23163b51b676d), it's great to see that generalised!
